# Generated by Django 4.2.6 on 2023-10-09 19:54

from django.db import migrations, models
import level_three.validators


class Migration(migrations.Migration):

    dependencies = [
        ('level_three', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=26, validators=[level_three.validators.check_for_m]),
        ),
    ]
